### ISSUE TITLE
07_handler.md 有一个小错误

### ISSUE THREAD

**Issue by codeQX** [jeanboydev/Android-ReadTheFuckingSourceCode#8]
[07_handler.md](https://github.com/jeanboydev/Android-ReadTheFuckingSourceCode/blob/master/article/android/basic/07_handler.md)
Handler 常用的方式：

`
// 使用方式二：handler.post()
handler.post(new Runnable() {
  @Override
  public void run() {
    // 运行在子线程中...
  }
});
`

这个run应该是运行在handler所在的线程中...
如果是主线程的Handler，run就执行在主线程，可以更新UI，setText等操作
如果是子线程的Handler，run就执行在子线程

**Comment by jeanboydev** [comment]
> [07_handler.md](https://github.com/jeanboydev/Android-ReadTheFuckingSourceCode/blob/master/article/android/basic/07_handler.md)
> Handler 常用的方式：
> 
> `// 使用方式二：handler.post() handler.post(new Runnable() { @Override public void run() { // 运行在子线程中... } });`
> 
> 这个run应该是运行在handler所在的线程中...
> 如果是主线程的Handler，run就执行在主线程，可以更新UI，setText等操作
> 如果是子线程的Handler，run就执行在子线程

 多谢您的建议，已经采纳
